Extend client in model-card with proxy endpoint.
intergiro/model-card pull request #195
Opened 2022-06-28 12:23 UTC by asnahassan

## Change
Extending client in model-card with the proxy endpoint and the merge function to combine body with the selector.

## Rationale
In order for all workers to use the proxy, we need a logic in model-card

## Impact
None

## Risk
This should have no increased risks on the system. No extra risk analysis is necessary.

## Rollback
For rollback, it is enough to revert the commit and redeploy.

2022-06-28 12:53 UTC, robinnedergard requested changes

2022-06-28 12:53 UTC, robinnedergard commented on Client/Card.ts
> +					? createBody(Object.assign({}, target), value, token)
I think this is exactly the same:
```suggestion
					? createBody({ ...target }, value, token)
```

2022-06-28 12:53 UTC, robinnedergard commented on Client/Card.ts
> +				!(Array.isArray(target) && Array.isArray(value)) && typeof target == "object" && typeof value == "object"
```suggestion
				!(Array.isArray(target) && Array.isArray(value)) && typeof target == "object" && typeof value == "object" && value && target
```

2022-06-28 12:53 UTC, robinnedergard commented on Client/Card.spec.ts
> +				{ amount: 57, currency: "EUR", card: { expires: [5, 23] } },
What happens if there are still csc and pan properties (not spelled CVV and PAN), will they still remain there?

2022-06-28 16:19 UTC, robinnedergard approved these changes

2022-07-04 14:51 UTC, Magnus93 requested changes

2022-07-05 12:30 UTC, merged