Added Card.Creatable.Safe type - parity
intergiro/model-card pull request #198
Opened 2022-06-30 12:15 UTC by nilssonemma

## Change
Added Card.Creatable.Safe type

## Rationale
Needed to be used in non pci workers

## Impact
No impact

## Risk
This should have no increased risks on the system. No extra risk analysis is necessary.

## Rollback
For rollback, it is enough to revert the commit and redeploy.

2022-06-30 13:25 UTC, robinnedergard requested changes

2022-06-30 13:25 UTC, robinnedergard commented on Card/Creatable/Safe.ts
> +						typeof value.verification.data == "object")))
```suggestion
						typeof value.verification.data == "object" && value.verification.data != null)))
```

2022-06-30 13:25 UTC, robinnedergard commented on Card/Creatable/Safe.ts
> +				(typeof value.verification == "object" &&
add != null check

2022-07-02 12:54 UTC, asnahassan approved these changes

2022-07-04 09:59 UTC, robinnedergard approved these changes

2022-07-05 09:04 UTC, Magnus93 approved these changes

2022-07-05 09:05 UTC, merged