Added headers to proxy client as optional.
intergiro/model-card pull request #200
Opened 2022-07-07 11:25 UTC by asnahassan

## Change
Added header in proxy client as optional.

## Rationale
To make it possible to use a generic proxy configuration that requires extra headers.

## Impact
None

## Risk
This should have no increased risks on the system. No extra risk analysis is necessary.

## Rollback
For rollback, it is enough to revert the commit and redeploy.

2022-07-08 14:05 UTC, Magnus93 requested changes

2022-07-08 14:05 UTC, Magnus93 commented on Client/Card.ts
> +				...(header ?? {}),
Since the same logic is used twice, it's probably better to save the `path` and the `headers` to variables before setting them in both if-blocks.

2022-07-12 14:21 UTC, nilssonemma approved these changes

2022-08-01 08:33 UTC, Magnus93 requested changes
fix package-lock conflict and for the parity branch

2022-08-02 09:07 UTC, Magnus93 approved these changes

2022-08-02 09:08 UTC, merged